# A list of IP addresses: 
#   hacc-build-01: 10.1.212.110
#   alveo-u250-01: 10.253.74.12
#   alveo-u250-02: 10.253.74.16
#   alveo-u250-03: 10.253.74.20
#   alveo-u250-04: 10.253.74.24
#   alveo-u250-05: 10.253.74.28
#   alveo-u250-06: 10.253.74.40

num_FPGA : 1

CPU_IP_addr : "10.1.212.110"
FPGA_IP_addr : ["10.253.74.16"]
C2F_port: [8881]
F2C_port: [5001]

# Fixed parameters
D: 1024
TOPK: 100

# Tunable parameters at runtime
batch_size: 1
total_batch_num: 1000
nprobe: 32
nlist: 32768

# query window size controls the communication between CPU and FPGA
# this number shouldn't be set to too large, otherwise the FPGA will be overwhelmed by retranmissions
query_window_size: 2

# batch window size controls the speed of index scan on CPU 
batch_window_size: 1
# enable_index_scan controls whether to enable index scan on CPU
enable_index_scan: 0

# CPU cores used for the entire CPU program 
cpu_cores: 8
